/**
 * Project-type-specific knowledge injected into AI node system prompts and utilities.
 *
 * This is the single source of truth for all framework-specific content.
 * Adding a new framework means adding one entry per exported function here —
 * every node and utility stays clean by importing what it needs.
 *
 * Exported API:
 *   buildConstraints(flags)         — project constraint block for all nodes
 *   buildResearchDirective(type)    — investigation rules for the researcher
 *   buildTddDirective(type)         — TDD section for planner / project manager
 *   buildCoderDirective(type)       — extra instructions for the coder
 *   getBuildCommandRe()             — regex matching framework build commands
 *   UNITY_ASSET_EXTENSIONS          — Set of Unity non-code asset file extensions
 */

// ---------------------------------------------------------------------------
// Constraints — injected into every node's system prompt
// ---------------------------------------------------------------------------

/**
 * Returns the project-type constraint block for all AI nodes.
 * Accepts the flags object produced by detectProjectContext().
 */
export function buildConstraints({ unity, isSwift, isCSharp, isPhp, isNode, isSilverStripe, isGodot }) {
  if (unity)          return UNITY_CONSTRAINTS;
  if (isSwift)        return SWIFT_CONSTRAINTS;
  if (isGodot)        return GODOT_CONSTRAINTS;
  if (isSilverStripe) return SILVERSTRIPE_CONSTRAINTS;
  if (isCSharp)       return CSHARP_CONSTRAINTS;
  if (isPhp)          return PHP_CONSTRAINTS;
  if (isNode)         return NODE_CONSTRAINTS;
  return UNKNOWN_CONSTRAINTS;
}

const UNITY_CONSTRAINTS = `[PROJECT TYPE: Unity C#]
CRITICAL UNITY CONSTRAINTS — MUST FOLLOW:
- ALL C# scripts MUST be placed under Assets/ (typically Assets/Scripts/ or a named feature subfolder). NEVER place scripts in Library/, Temp/, obj/, Packages/, or the project root.
- Do NOT mandate TDD or write test files first. Unity tests require the Unity Test Runner inside the Unity Editor and CANNOT be run from the CLI, dotnet test, or batchmode without a specific test project setup. Only add test subtasks if the original task explicitly requests Edit Mode or Play Mode tests.
- NEVER run "dotnet build" or "dotnet test" on a Unity project. Unity manages its own Roslyn compilation pipeline via the UnityEditor. Running dotnet on a Unity project will fail.
- The Unity project's .sln and .csproj files are AUTO-GENERATED by Unity. Do NOT manually edit them.
- UXML files are XML-based UI layout files. USS files are CSS-like stylesheets. Neither requires C# compilation — write them with correct XML/CSS syntax only.
- C# scripts that use UnityEngine types MUST include "using UnityEngine;" at the top. Editor-only scripts (in an "Editor/" subfolder) MUST include "using UnityEditor;".
- MonoBehaviour subclasses MUST be in a file whose name matches the class name exactly (e.g. PlayerController.cs for class PlayerController).
- Namespaces in C# scripts should match the folder structure under Assets/ to avoid assembly conflicts.
- Assembly Definition (.asmdef) files control which scripts belong to which assembly. If a new script should belong to an existing assembly, place it in the correct folder — do not modify .asmdef files unless specifically required.`;

const GODOT_BIN_PATH = "/mnt/c/Users/Work/Godot_v4.6.2-stable_win64.exe/Godot_v4.6.2-stable_win64_console.exe";
const GODOT_CONSTRAINTS = `[PROJECT TYPE: Godot 4 / GDScript]
CRITICAL GODOT CONSTRAINTS — MUST FOLLOW:

SYNTAX VERIFICATION (MANDATORY after every .gd file write):
- After writing or patching any .gd file, verify with:
  GODOT_BIN=${GODOT_BIN_PATH}
  WIN_PATH = project path in Windows format (e.g. C:/Users/Work/card_game — NOT the /mnt/c/ WSL form)
  execute_bash("\\\"$GODOT_BIN\\\" --headless --path \\\"$WIN_PATH\\\" --check-only --quit 2>&1")
  Exit code 0 with no "SCRIPT ERROR" lines = syntax clean. Any error = fix before proceeding.

GDSCRIPT 4 SYNTAX RULES (violations cause SCRIPT ERROR at --check-only time):
- All .gd files MUST start with: extends <NodeType>  (e.g. extends Node, extends Control)
- Variable declarations: "var name: Type = value" — NOT bare "name: Type = value"
- Type hints: int, float, bool, String, Array[String], Dictionary, Vector2, Color
- Signal connections: signal_name.connect(callable) — NOT connect("signal_name", handler) (Godot 3 syntax)
- Autoloads accessed by registered name: GameState.player_hp — NOT $GameState or get_node(...)
- Dict access: dict.get("key", default) — NOT dict["key"] (crashes on missing key)
- String formatting: "text %s" % value or "text %d %d" % [a, b] — NOT Python f-strings
- super call: super.method_name() — NOT parent.method_name()
- Callable/lambda: func(x): return x*2 or method.bind(arg) for partial application
- Array size: array.size() — NOT len(array)
- Type test: value is TypeName — NOT isinstance(value, TypeName)

PATTERNS TO AVOID:
- No Python dict/list comprehensions (not supported)
- No := walrus operator
- No __init__() — use _init() or _ready()
- No Python-style *args or **kwargs

PROJECT STRUCTURE:
- Scripts: scripts/*.gd — each MUST have "extends" matching the scene node type
- Data: data/*.json — load with JSON.parse_string(FileAccess.get_file_as_string("res://data/file.json"))
- Scenes: scenes/*.tscn — NEVER edit .tscn files directly (managed by Godot editor)
- Tests: tests/TestRunner.gd (unit tests) and tests/Playthrough.gd (integration)
- Autoloads (global singletons): GameState, CardDB, Palette, SettingsManager, SaveManager

TESTING:
  GODOT_BIN=${GODOT_BIN_PATH}
- Unit tests: execute_bash("\\\"$GODOT_BIN\\\" --headless --path \\\"$WIN_PATH\\\" tests/Test.tscn 2>&1") — exits 0 = pass
- Playthrough: execute_bash("\\\"$GODOT_BIN\\\" --headless --path \\\"$WIN_PATH\\\" tests/Playthrough.tscn 2>&1") — exits 0 = pass
- When adding new features, add _assert() calls to tests/TestRunner.gd`;

const CSHARP_CONSTRAINTS = `[PROJECT TYPE: C# / .NET]
- Build: dotnet build <solution-or-project> --no-restore
- Test: dotnet test
- Do not apply Unity-specific constraints.`;

const SILVERSTRIPE_CONSTRAINTS = `[PROJECT TYPE: SilverStripe CMS (PHP)]
CRITICAL SILVERSTRIPE CONSTRAINTS — MUST FOLLOW:

DATABASE BUILDS:
- After ANY change to DataObject subclasses, Extensions, or _config YAML files, run:
  vendor/bin/sake db:build    (SilverStripe 5+)
  vendor/bin/sake dev/build flush=all    (SilverStripe 4)
- Use --flush on db:build only if it's a boolean flag (no value): vendor/bin/sake db:build --flush

INJECTOR YAML CONFIG (_config/*.yml):
- The CORRECT calls: format is a named key whose value is an inline sequence [methodName, [args]]:
    calls:
      myLabel: [pushHandler, ['%$Monolog\\Handler\\StreamHandler.myhandler']]
- The WRONG format (throws InvalidArgumentException) is a named key with a block-list value:
    calls:                   ← WRONG — DO NOT USE
      pushHandler:
        - ['%$...']
- Service references use %$ prefix with single backslashes for PHP namespaces: '%$Psr\\Log\\LoggerInterface'
- Named services use dot notation: 'Psr\\Log\\LoggerInterface.myname' — define the service under
  SilverStripe\\Core\\Injector\\Injector: at the same level as other services
- Service definitions (class:, constructor:, calls:) MUST live under SilverStripe\\Core\\Injector\\Injector:
  NOT at the top level of the YAML file

YAML CONFIG RULES:
- Use 2-space indentation, no tabs
- Document separators (---) are required between named config blocks
- Extensions attach via YAML, not by editing core classes:
    ClassName:
      extensions:
        - 'App\\Extension\\MyExtension'

TEMPLATE & PAGE RENDERING — CRITICAL:
SilverStripe is a web CMS. After ANY change to .ss templates, PHP page/controller classes,
DataObject subclasses, or DataExtensions, you MUST verify the site actually renders.

Step 1 — Discover the site base URL:
  grep SS_BASE_URL .env 2>/dev/null || grep -r "BASE_URL\\|ServerName\\|ServerAlias" /etc/apache2/sites-enabled/ 2>/dev/null | head -5

Step 2 — Flush the template/manifest cache (ALWAYS do this after template changes):
  vendor/bin/sake dev/build --flush
  OR append ?flush=1 to any URL you test

Step 3 — Test that the affected page(s) render without errors:
  Use http_request(url="{DISCOVERED_URL}/?flush=1") — check status and response body for exceptions.

Step 4 — If a specific page was broken (e.g. GET /events/my-event), test that URL too.

TEMPLATE RENDERING ERROR PATTERNS:
- BadMethodCallException: forTemplate does not exist on SomeClass
    → A .ss template renders a DataObject directly as a string (e.g. $SomeRelation with no property chain)
    → Fix A: In the template, change $SomeRelation to $SomeRelation.Title (or whichever scalar)
    → Fix B: Add forTemplate() to SomeClass returning a sensible string
    → Trace: grep the .ss template files for $ClassName (bare, no .Property chain)

- Method 'X' does not exist on 'SomeClass'
    → Template calls $X but neither the class nor its extensions define X()
    → Check YAML _config for extensions attached to that class
    → grep all DataExtension files for "public function X"

- Unexpected token / template parse error
    → .ss syntax error: unclosed <% if %>, missing <% end_if %>, bad variable syntax
    → Check .ss file line numbers from the error message

GENERAL:
- Dependency management: composer
- Tests: vendor/bin/phpunit or vendor/bin/sake dev/tests
- Static analysis: vendor/bin/phpstan (if present)
- NEVER edit files under vendor/ — use YAML config overrides and extensions instead`;

const PHP_CONSTRAINTS = `[PROJECT TYPE: PHP / Laravel]
- Dependency management: composer
- Tests: vendor/bin/phpunit
- Static analysis: vendor/bin/phpstan`;

const NODE_CONSTRAINTS = `[PROJECT TYPE: Node.js / TypeScript]
- Dependency management: npm / yarn / pnpm
- Tests: vitest or jest
- Type checking: npx tsc --noEmit

PROJECT SETUP (MANDATORY for all new Node.js / React / Vite projects — enforced by verifier):
- GITIGNORE FIRST: The VERY FIRST file written for any new project MUST be .gitignore. It MUST contain at minimum: node_modules/, dist/, .env, *.log, .DS_Store, coverage/, .vite/. Skipping this causes git to track thousands of dependency files — the verifier will reject the subtask.
- README REQUIRED: Every new project MUST include README.md with: project name, one-line description, and the commands: npm install, npm run dev, npm run build, npm test.
- NO FAKE DEPS: NEVER add non-package entries to package.json dependencies or devDependencies. Keys starting with "#" (e.g. "#test-run", "#acceptance-test", "#marker") are NOT valid npm syntax and will be detected and rejected by the verifier. Track task completion in code or comments — never in package.json.
- NO DEV SERVER IN EXECUTE_BASH: NEVER run "npm run dev", "vite", "next dev", or any other long-running dev server command via execute_bash. These commands block forever and will time out. The verifier automatically starts and stops the dev server — you do NOT need to do this.`;

const UNKNOWN_CONSTRAINTS = `[PROJECT TYPE: Unknown — explore the project structure before making assumptions about tooling or conventions]`;

const SWIFT_CONSTRAINTS = `[PROJECT TYPE: Swift / Xcode]
CRITICAL SWIFT CONSTRAINTS — MUST FOLLOW:
- Do NOT run "xcodebuild" or "swift build" as a compilation step — the build environment may not have the required signing certificates or SDK configuration. Verify syntax with "swiftc -parse <file>" only.
- Swift files MUST follow the module structure expected by the Xcode project. Do not create new Swift files outside of existing source groups without reading the .xcodeproj or Package.swift first.
- If the project uses Swift Package Manager (Package.swift present), new source files belong under Sources/<TargetName>/. If it is an Xcode project, place files in the appropriate group folder matching the existing structure.
- UIKit apps use UIViewController subclasses and Storyboards/XIBs. SwiftUI apps use View structs. Do not mix paradigms unless the codebase already does so.
- .storyboard and .xib files are XML-based UI layout files. Editing them with write_file is valid; do NOT attempt to compile or validate them beyond checking XML syntax.
- Swift test targets use XCTest. Tests live under <ProjectName>Tests/ (Xcode) or Tests/<TargetName>Tests/ (SPM). Do not run tests from CLI without explicit user request.
- CocoaPods projects have a Podfile and <ProjectName>.xcworkspace. Always open the workspace (not .xcodeproj) when using the Xcode toolchain.
- Do NOT edit files under Pods/ — use the Podfile to manage CocoaPods dependencies.`;

// ---------------------------------------------------------------------------
// Research directive — injected into the researcher system prompt
// ---------------------------------------------------------------------------

/**
 * Returns the researcher investigation directive for the given project type.
 * Injected into the researcher system prompt after the general research rules.
 */
export function buildResearchDirective(projectType) {
  if (projectType === "unity")        return UNITY_RESEARCH_DIRECTIVE;
  if (projectType === "silverstripe") return SILVERSTRIPE_RESEARCH_DIRECTIVE;
  if (projectType === "swift")        return SWIFT_RESEARCH_DIRECTIVE;
  if (projectType === "godot")        return GODOT_RESEARCH_DIRECTIVE;
  return "";
}

const UNITY_RESEARCH_DIRECTIVE = `

UNITY PROJECT DETECTED. During your research you MUST specifically investigate:
1. Read ProjectSettings/ProjectVersion.txt to identify the Unity version.
2. List all .asmdef files under Assets/ to understand assembly boundaries.
3. Map the folder structure under Assets/Scripts/ (or equivalent) to determine where new scripts belong.
4. Read nearby .cs files to identify namespaces already in use.
5. Determine whether the project uses UI Toolkit (look for .uxml/.uss files) or Legacy UI (UGUI Canvas components).
6. Identify any existing MonoBehaviour or ScriptableObject base classes that new code should inherit from.
7. Check for Editor-only folders (subfolders named "Editor/") - scripts there use UnityEditor assembly and must not be referenced from runtime code.
DO NOT attempt to run dotnet build, dotnet test, or any compilation command - Unity projects cannot be built outside the Unity Editor.`;

const SILVERSTRIPE_RESEARCH_DIRECTIVE = `

SILVERSTRIPE PROJECT DETECTED. During your research you MUST specifically investigate:

RESEARCH EFFICIENCY (MANDATORY — prevents runaway research phase):
- Do NOT read the same file twice. Keep a mental list of files already read and skip duplicate read_file or execute_bash calls for the same path.
- Do NOT run the same grep command twice. If you've already searched for a pattern, trust the earlier result.
- Stop adding tool calls once you have sufficient evidence for every section of KEY FINDINGS. Research that runs for 30+ minutes burns the session budget before any code is written.
- If a file read reveals nothing relevant to the task, stop reading it — do not paginate to additional sections "just in case".

1. Read composer.json to identify the SilverStripe version (look for silverstripe/framework constraint).
2. List all files under app/_config/ (or mysite/_config/) and READ EVERY ONE OF THEM — not just files that seem relevant. A feature you think is missing may already be configured in a file you haven't read.

ALREADY-IMPLEMENTED CHECK (CRITICAL — prevents infinite retry loops):
After reading all _config files, check whether the task's core feature is already in place:
- If the task asks to add Elemental extensions and you find DNADesign\Elemental\Extensions\ElementalPageExtension in any _config YAML → include in KEY FINDINGS SUMMARY: "⚠️ ELEMENTAL ALREADY CONFIGURED: extensions are already attached in [filename]. Do NOT re-add them. Only add what is genuinely missing."
- If the task involves Elemental blocks/content areas: run execute_bash("composer show dnadesign/silverstripe-elemental 2>&1") to check if it is installed transitively. If it IS installed (even via silverstripe/recipe-cms), include: "⚠️ ELEMENTAL ALREADY INSTALLED (transitively via silverstripe/recipe-cms) — do NOT generate a composer require subtask. In SS6, dnadesign/silverstripe-elemental is included in silverstripe/recipe-cms. Adding it directly will trigger unintended upgrades of all dependencies."
- If the task asks to install a Composer package and you find it already in composer.json → include: "⚠️ ALREADY INSTALLED: [package] is already in composer.json at version [X]. Verify it is working before adding it again."
- Generally: if ANY required component is already present, say so explicitly so the planner does NOT generate subtasks to re-create it.

CLASS EXISTENCE VERIFICATION (prevents "references nonexistent class" loops):
Before reporting any PHP class name in your research summary, verify it exists:
- For extension classes being attached via YAML: grep vendor/dnadesign -r "class ClassName" to confirm the class file exists
- NEVER cite SilverStripe\Elemental\* class names — the Elemental package uses the DNADesign\Elemental\* namespace
- Correct Elemental extension class: DNADesign\Elemental\Extensions\ElementalPageExtension (confirmed by find vendor/dnadesign -name "ElementalPageExtension.php")
- DNADesign\Elemental\Extensions\ElementalCMSMainExtension does NOT exist in current versions — do NOT use it
- Wrong (do not use): SilverStripe\Elemental\Extensions\ElementalAreasExtension (this class does NOT exist)

YAML BACKSLASH ESCAPING (prevents \ElementalPageExtension parse error):
PHP namespace separators are single backslashes. In YAML:
- CORRECT: unquoted class names — DNADesign\Elemental\Extensions\ElementalPageExtension
- CORRECT: double-quoted with \\ — "DNADesign\\Elemental\\Extensions\\ElementalPageExtension"
- WRONG: single-quoted with \\ — 'DNADesign\\Elemental\\Extensions\\ElementalPageExtension'
  Single-quoted YAML strings do NOT process escape sequences. '\\' = two literal backslashes.
  This causes PHP's token_get_all to produce \ElementalPageExtension (bare global namespace).
Always use UNQUOTED class names in YAML extensions: lists unless the class name contains special YAML characters.

3. If the task involves an error with "Injector.php" in the stack trace:
   a. grep for "calls:" across all _config YAML files
   b. For each calls: block found, verify the format is: myLabel: [methodName, ['%$ServiceName']]
      NOT: methodName:\\n        - [args]  (this block-sequence format causes InvalidArgumentException)
   c. Check service references for double backslashes ('\\\\') - they must use single backslashes ('\\')
   d. Verify named services (dot notation like 'Psr\\Log\\LoggerInterface.myname') are defined under
      SilverStripe\\Core\\Injector\\Injector: - NOT at the top level of the YAML file
4. List DataObject subclasses in app/src/ (or mysite/code/) relevant to the task.
5. Check for any existing extensions registered in YAML (search for "extensions:" in _config files).
6. Identify whether the project uses SS4 (dev/build flush=all) or SS5+ (db:build --flush) sake commands.
7. For any _config YAML change, note that vendor/bin/sake db:build must be run afterwards to verify.

SCSS / CSS BUILD SYSTEM DETECTION (MANDATORY when the task involves CSS, SCSS, or visual layout):
If the task involves any CSS or SCSS change, you MUST identify the build system before any SCSS is written:
a. Check for a package.json with a "build" or "watch" script: execute_bash("cat themes/*/app/package.json 2>/dev/null || cat package.json")
   If found with a vite/webpack/sass build script, note: "⚠️ SCSS SOURCE MUST BE COMPILED — run build command after editing SCSS. SCSS source changes do NOT take effect until compiled to dist/."
b. Locate the compiled CSS output: execute_bash("find themes -name 'main.css' -o -name '*.min.css' 2>/dev/null | grep dist | head -5")
   Include the compiled output path in KEY FINDINGS SUMMARY so the coder knows where to verify after building.
c. Include in KEY FINDINGS SUMMARY the exact build command, e.g.:
   "⚠️ BUILD REQUIRED after SCSS changes: cd /var/www/[project]/themes/[theme]/app && npm run build"
   "Compiled CSS output: themes/[theme]/app/dist/main.css"
   "VERIFICATION: grep the compiled CSS for the selector, NOT the SCSS source."

CSS SELECTOR PITFALL FOR GRID LAYOUT TASKS (CRITICAL — prevents wrong :last-child selector):
If the task involves targeting the "last item" in a CSS Grid:
a. Read the SilverStripe .ss template that renders the grid container.
b. Identify ALL child element types inside the grid container — there may be decorative <img> or <span> elements AFTER the last repeating item.
c. If the last child in the DOM is NOT the last repeating item (e.g. a trailing <img> or wrapper div exists after the loop), then:
   - ".repeating-class:last-child" will NEVER match — the last child is the non-matching element.
   - CORRECT approach: use ":last-of-type" on the repeating element's HTML tag (e.g. "a:last-of-type") if they're all the same tag,
     OR use a modifier class (e.g. ".is-last") added in the SilverStripe template via <% if $Last %>.
   - OR target the actual last child element directly (e.g. "img:last-of-type" if a trailing image is the true last child).
   - CSS GRID SPAN-TO-END PITFALL: To make an item span from its auto-placed column to the last column, use the LONGHAND:
       "grid-column-start: auto; grid-column-end: -1"
     Do NOT use the shorthand "grid-column: auto / -1" — in the shorthand, auto resolves to span-1-from-end = last column only. The longhand grid-column-start: auto means the auto-placement algorithm independently decides the start position (e.g. col3), and grid-column-end: -1 then spans from there to the last grid line.
d. Include in KEY FINDINGS SUMMARY: the exact HTML tag of the last child, and which selector correctly targets the last repeating item.

CMS FIELD SUPPRESSION INVESTIGATION (MANDATORY when the task involves Elemental area not visible in CMS, getCMSFields, or CMS field layout):
Run ALL of these checks — CMS field suppression bugs are almost always caused by one of these patterns:
a. execute_bash("grep -rn 'removeByName' app/src/") — scan ALL PHP files for removeByName calls.
   Flag any removeByName('Content'), removeByName('ElementalArea'), removeByName('ElementalAreaID'),
   removeByName('Root.Main'), or removeByName('Root') found in getCMSFields() or updateCMSFields().
b. execute_bash("grep -rn 'getCMSFields' app/src/") — list all getCMSFields() overrides.
   For each override found: read_file the containing file and check:
   - Does it call parent::getCMSFields()? If NOT, it replaces the entire field set — Elemental is lost.
   - Does it call $fields->removeByName('ElementalArea') or tab manipulation that hides the block editor?
c. execute_bash("grep -rn 'updateCMSFields' app/src/") — list all DataExtension updateCMSFields() hooks.
   Extensions that call removeByName() here can silently suppress the Elemental area.
d. execute_bash("grep -rn 'TabSet\\|addFieldToTab\\|removeFieldsFromTab' app/src/") — tab rebuild patterns.
   A full TabSet rebuild in getCMSFields() discards all fields added by extensions (including Elemental).
Include ALL findings in your KEY FINDINGS SUMMARY so the scoper can generate precise fix subtasks.

SITE URL DISCOVERY (MANDATORY — do this before any http_request call):
8. Read the project root .env file and extract SS_BASE_URL. Use that URL for ALL http_request calls.
   Do NOT assume http://localhost — many SilverStripe installs run on a named vhost and will return
   404 at localhost. If SS_BASE_URL is not set, check Apache/nginx vhost config in /etc/apache2/
   or /etc/nginx/sites-enabled/ for the ServerName / server_name.
   Use the discovered URL for all verification calls. Example:
     grep -E "^SS_BASE_URL" .env  →  SS_BASE_URL="https://mysite.local"
   Then all verification calls use: http_request(url="https://mysite.local/?flush=1")

TEMPLATE & RENDERING ERROR INVESTIGATION (run these whenever the task involves a template crash or rendering issue):
9. After discovering the base URL, immediately test the live page:
   http_request(url="\${BASE_URL}/?flush=1")
   Status 500 with SilverStripe error HTML = active rendering failure. Status 200 = currently passing.
   The http_request tool automatically extracts SilverStripe exception details from the response HTML.
10. For "MissingTemplateException" or any template-not-found error (the most common Elemental failure):
    SilverStripe maps PHP namespaces to template paths. The class "Vendor\\Module\\Elements\\MyBlock"
    requires a template at: themes/{theme}/templates/Vendor/Module/Elements/MyBlock.ss
    OR under app/templates/ using the same namespace-to-path conversion.
    a. Run: find_file with the class short name (e.g. "MyBlock.ss") to see if ANY template exists.
    b. Check which themes are active: grep -r "SSViewer" app/_config/ or check SiteConfig.
    c. The theme order in config determines the lookup path (e.g. ["$public", "simple", "$default"]).
    d. Template must be in ONE of those theme directories under templates/{Namespace}/{Class}.ss
    e. For Elemental block elements, ALSO check for a {ClassName}_ElementalArea.ss variant.
11. For Elemental blocks specifically — required components checklist:
    a. YAML extension config: Page class has DNADesign\\Elemental\\Extensions\\ElementalPageExtension
       (ElementalCMSMainExtension does NOT exist in current package versions — do NOT include it)
    b. Page template (Layout/Page.ss or similar): contains $ElementalArea variable
    d. Each Element class has a corresponding .ss template in the correct theme path
    e. vendor/bin/sake db:build has been run after any YAML changes
    Verify EACH of these with read_file or find_file. Any missing = ❌ MISSING in FEATURE GAP ANALYSIS.
12. For template parse errors or "method does not exist" errors:
    a. Identify the .ss template from the URL (GET /path → find the Page class → find its Layout template)
    b. grep all .ss files for the missing method/variable name to find where it is called
    c. Check whether the method is on the class, its parent, or a registered extension
13. After any fix, verify the page renders clean:
    http_request(url="\${BASE_URL}/?flush=1") — check for 200 status and no exception text in body.

"REFERENCES NONEXISTENT \\ClassName IN 'EXTENSIONS'" DIAGNOSIS:
This error fires from ExtensionMiddleware.php when an extension class registered
in YAML cannot be found. The leading \\ on the class name is the diagnostic tell:

STEP 1 — Determine if the class truly doesn't exist OR just has a name format bug:
  execute_bash("php -r \\"require 'vendor/autoload.php'; echo class_exists('DNADesign\\\\\\\\Elemental\\\\\\\\Extensions\\\\\\\\ElementalPageExtension') ? 'EXISTS' : 'NOT FOUND';\\"")
  (Replace with the actual class name from the error message, without the leading \\\\)
  - "EXISTS"   → class is loadable. The bug is in the YAML format, not the class.
  - "NOT FOUND" → class genuinely missing. Check vendor or remove the extension entry.

STEP 2 (if EXISTS) — Find the YAML file with the bad format:
  execute_bash("grep -rn \\"extensions:\\" app/_config/")
  Then read each file. Look for extension class names wrapped in single quotes with double
  backslashes, e.g. '- \\'DNADesign\\\\\\\\Elemental\\\\\\\\Extensions\\\\\\\\ElementalPageExtension\\''.
  The single quotes cause '\\\\\\\\' to be two literal backslashes at runtime → PHP tokenizer
  splits DNADesign\\\\Elemental into DNADesign + \\\\ElementalPageExtension.

STEP 3 — Fix and clear the compiled config cache:
  Fix: Remove the single quotes from the class name in the YAML file (unquoted = correct).
  Then clear the cache: execute_bash("rm -rf /tmp/silverstripe-cache-$(echo {PROJECT_DIR} | tr '/' '-' | sed 's/^-//')/www-data-*/configcache /tmp/silverstripe-cache-$(echo {PROJECT_DIR} | tr '/' '-' | sed 's/^-//')/$(whoami)-*/configcache 2>/dev/null; echo done")
  A simpler broad clear: execute_bash("find /tmp -maxdepth 3 -name 'configcache' -exec rm -rf {} + 2>/dev/null; echo done")
  Then re-verify with http_request or vendor/bin/sake db:build.

SS MANIFEST CACHE LOCATION:
SilverStripe's compiled config/class manifest lives in /tmp/silverstripe-cache-{path}/,
NOT in the project directory. Specifically:
  /tmp/silverstripe-cache-var-www-{project}/www-data-{phpver}/   ← web server (Apache/nginx)
  /tmp/silverstripe-cache-var-www-{project}/{user}-{phpver}/      ← CLI (sake)
If the YAML source is clean but the error persists after a flush, the configcache
contains stale bad data from a previous broken request. Clear it with:
  execute_bash("find /tmp -maxdepth 3 -name 'configcache' -exec rm -rf {} + 2>/dev/null; echo done")
Always clear both the www-data and current-user cache dirs.`;

const SWIFT_RESEARCH_DIRECTIVE = `

SWIFT PROJECT DETECTED. During your research you MUST specifically investigate:
1. Determine whether the project uses Swift Package Manager (Package.swift present) or Xcode project (.xcodeproj present) or both (CocoaPods workspace).
2. If SPM: read Package.swift to identify targets, their source directories, and dependencies.
3. If Xcode project: list the top-level directory to identify the main source group folder (usually named after the app).
4. Identify the minimum deployment target (iOS/macOS/watchOS/tvOS version) from Package.swift or the Xcode project settings (look for IPHONEOS_DEPLOYMENT_TARGET or MACOSX_DEPLOYMENT_TARGET in *.xcconfig files or project.pbxproj).
5. Determine the UI paradigm: look for SwiftUI (import SwiftUI, @main App struct) vs UIKit (AppDelegate, UIViewController subclasses) vs AppKit (NSViewController). Mixed codebases may use both.
6. Read nearby .swift files relevant to the task to identify existing patterns, naming conventions, and module imports.
7. Check for a Podfile — if present, list pod dependencies relevant to the task.
8. Check for any existing test targets (XCTestCase subclasses) in the Tests/ folder or <ProjectName>Tests/ group.

9. PRE-FLIGHT TYPE CHECK (MANDATORY — run this early in research):
   execute_bash: cd <projectDir> && swiftc -typecheck -sdk "$(xcrun --show-sdk-path)" $(find . -name '*.swift' -not -path '*/Pods/*' -not -path '*/.build/*' -not -path '*Tests*') 2>&1 | head -60
   Include the FULL output in your KEY FINDINGS SUMMARY under "EXISTING TYPE ERRORS (pre-flight)". Even if the output looks like context lines only, include it — the pipeline uses it to detect cascade masking.
   NOTE: "no such module 'UIKit'" errors from macOS SDK are a known false positive (UIKit is iOS-only) but they MASK other real errors. If you see only a UIKit cascade, explicitly note: "WARNING: UIKit import in [file] may be masking additional type errors. The coder must remove or isolate the UIKit import to unblock cascade detection."

10. CHECK APP ENTRY POINT (*App.swift) for known type errors (MANDATORY — do not skip):
    Read the *App.swift file (the file with @main). Grep for .preferredColorScheme:
    execute_bash: grep -n "preferredColorScheme" <App.swift path>
    Then read the file to determine context. If .preferredColorScheme(...) appears AFTER the closing } of a WindowGroup {} block (i.e., at the same indentation level as "WindowGroup" or less — applied to the Scene result, not inside the View), you MUST flag this EXPLICITLY in KEY FINDINGS SUMMARY as:
    "KNOWN TYPE ERROR: .preferredColorScheme is a View modifier called on a Scene (WindowGroup) in [filename]:line [N]. The planner MUST create a subtask to fix this BEFORE any feature subtasks. Fix: WindowGroup { Group { ContentView() }.preferredColorScheme(...) }"
    This error is ALWAYS masked by swiftc -typecheck cascade errors and ALWAYS causes verifier rejection. The planner cannot skip creating a fix subtask for this.

11. CHECK UIKit IN SWIFTUI FILES:
    execute_bash: grep -rn "import UIKit" <sourceDir>/
    For each file that imports UIKit AND defines a SwiftUI View (imports SwiftUI + struct ... View), note: "UIKit import in [file] causes cascade errors in the macOS SDK type-checker, masking unrelated errors elsewhere. Coder must be aware of this."
    Also grep for UIKit-dependent API usage that must be replaced when UIKit is removed:
    execute_bash: grep -rn "systemBackground\|systemOrange\|UIPasteboard\|UIApplication\|UIActivityViewController\|UINotificationFeedbackGenerator\|UIViewController" <sourceDir>/
    List all occurrences in KEY FINDINGS SUMMARY — these must ALL be replaced atomically when UIKit is removed (cannot remove UIKit import separately from these API calls).

12. CHECK FOR DEPRECATED API PATTERNS (iOS 17+):
    execute_bash: grep -rn "\.onChange(of:" <sourceDir>/ | grep -v "old.*,.*new\|,.*in"
    If any .onChange(of:) calls use a single-parameter closure form (e.g. { newPhase in ... }), flag as:
    "DEPRECATED API: onChange(of:perform:) single-param form at [file]:line [N]. Fix: use two-param form { oldVal, newVal in ... } or zero-param form."
    The verifier detects this pattern statically and will REJECT the acceptance test if found.
    Also check: execute_bash: grep -rn "\.navigationBarTitle\|\.foregroundColor\|\.accentColor\|\.listRowBackground\|ButtonStyle(BorderlessButtonStyle\|ButtonStyle(PlainButtonStyle" <sourceDir>/
    These APIs have iOS 17 replacements. Flag any found for the planner to include fix subtasks.

13. CHECK FOR SWIFT 6 ACTOR ISOLATION ISSUES:
    execute_bash: grep -rn "addObserver.*forName:" <sourceDir>/
    For each NotificationCenter.addObserver call, check if the closure body (within the same file) directly accesses @StateObject or @ObservedObject properties (e.g. viewModel.someMethod()). If found WITHOUT Task { @MainActor in ... } wrapping, flag as:
    "CONCURRENCY ISSUE: NotificationCenter closure at [file]:line [N] accesses @MainActor viewModel directly — Swift 6 error. Preferred fix: replace with scenePhase onChange."
    ALSO CHECK FOR REDUNDANT+BROKEN COEXISTENCE:
    execute_bash: grep -rn "scenePhase" <sourceDir>/ | grep "onChange"
    If the project has BOTH:
      (a) NotificationCenter.addObserver (in any view file, e.g. ContentView.swift) AND
      (b) scenePhase .onChange (in any App struct file, e.g. *App.swift) targeting the same save/lifecycle operation
    Then flag as: "REDUNDANT+BROKEN: [ContentView.swift] has NotificationCenter.addObserver calling viewModel.saveAllData() but [*App.swift] already uses scenePhase .onChange for the same purpose. The NotificationCenter code in ContentView.swift is BOTH redundant AND a Swift 6 MainActor isolation error — it MUST be removed entirely (remove the observer property, the .onAppear registration, and the .onDisappear deregistration)."

14. CHECK FOR @Observable / ObservableObject CONSISTENCY:
    execute_bash: grep -rn "@Observable" <sourceDir>/
    execute_bash: grep -rn "ObservableObject" <sourceDir>/
    execute_bash: grep -rn "@StateObject\|@ObservedObject\|@Bindable" <sourceDir>/
    If you find classes declared with @Observable AND any consuming view still using @StateObject or @ObservedObject to reference those same classes, flag as:
    "CRITICAL CONSISTENCY ERROR: [ViewModel] is declared with @Observable but [ViewFile] still uses @StateObject/@ObservedObject — these are mutually exclusive. @Observable requires @State (owner) and @Bindable (receivers); ObservableObject requires @StateObject (owner) and @ObservedObject (receivers)."
    If you find BOTH @Observable and ObservableObject conformances on classes in the same project, determine which pattern the project intends to use and flag ALL mismatches.
    KEY FINDING FORMAT: "OBSERVABLE MISMATCH: [file]:line [N] — [ClassName] is @Observable but [view] wraps it with @StateObject/@ObservedObject. Migration MUST be atomic across ALL files."

DO NOT attempt to run xcodebuild or swift build — the pipeline cannot sign or resolve the full Xcode build graph.`;

const GODOT_RESEARCH_DIRECTIVE = `

GODOT PROJECT DETECTED. During your research you MUST specifically investigate:
1. Read project.godot to identify the Godot version and which autoloads are registered.
2. Read ALL scripts in scripts/ — especially autoloads (GameState.gd, CardDB.gd, etc.) to understand the data model and existing API.
3. For tasks adding cards/enemies/relics/events: read the corresponding data/*.json file to understand the schema before writing new entries.
4. Run the baseline syntax check to confirm the project is clean before any changes:
   GODOT_BIN=${GODOT_BIN_PATH}
   execute_bash("\\"$GODOT_BIN\\" --headless --path \\"C:/Users/Work/card_game\\" --check-only --quit 2>&1")
   Include the full output in KEY FINDINGS SUMMARY. If errors exist, note them.
5. Run the baseline unit tests:
   execute_bash("\\"$GODOT_BIN\\" --headless --path \\"C:/Users/Work/card_game\\" tests/Test.tscn 2>&1")
   Include full output in KEY FINDINGS SUMMARY (pass/fail count).
6. Identify which scripts and data files need modification for the task.
7. Check tests/TestRunner.gd to understand existing test coverage and how to add new tests.

ALREADY-IMPLEMENTED CHECK (prevents duplicate work):
- Before generating subtasks to add cards/enemies/relics/events, always check the data JSON files first.
- If any requested feature already exists: include in KEY FINDINGS SUMMARY: "⚠️ ALREADY PRESENT: [feature] in [file]. Only add what is genuinely missing."`;

// ---------------------------------------------------------------------------
// TDD directive — injected into planner and project manager system prompts
// ---------------------------------------------------------------------------

/**
 * Returns the TDD mandate section for the given project type.
 * Used by plannerNode and projectManagerNode.
 */
export function buildTddDirective(projectType) {
  if (projectType === "unity") return UNITY_TDD_DIRECTIVE;
  if (projectType === "swift") return SWIFT_TDD_DIRECTIVE;
  if (projectType === "godot") return GODOT_TDD_DIRECTIVE;
  if (projectType === "node" || projectType === "unknown") return NODE_TDD_DIRECTIVE;
  return GENERIC_TDD_DIRECTIVE;
}

const UNITY_TDD_DIRECTIVE = `IMPORTANT: This is a Unity project. Do NOT mandate writing unit test files first and do NOT create subtasks whose primary output is a test file. Unity tests require the Unity Test Runner inside the Unity Editor and cannot be run from the CLI or batchmode. Only include test subtasks if the original user task explicitly requests Edit Mode or Play Mode tests.`;

const NODE_TDD_DIRECTIVE = `You are encouraged to apply TDD where natural. For JS/TS projects, writing a failing test first is appropriate — BUT ONLY if the source module it imports already exists. If both the source module AND the test file are being created as part of this plan, the source module subtask MUST come first. NEVER create a test subtask that imports a not-yet-existing module before the module creation subtask. For other project types, only add test subtasks if the task explicitly requires them.

ANTI-STUB RULE (CRITICAL): When the task requires implementing logic (getLegalMoves, validateMove, calculateScore, etc.), the implementation subtask MUST produce a REAL implementation — NOT a stub that returns [] or false or null. A test subtask that passes because the implementation is an empty stub is a false pass and a pipeline failure. The implementation note MUST explicitly say "REAL implementation required — do NOT return [] or placeholder values." If a function cannot be fully implemented yet (dependency not ready), create the dependency first as its own subtask, then implement the function.`;

const GENERIC_TDD_DIRECTIVE = `Only add test subtasks if the task explicitly requires them. Do not force TDD for non-JS/TS projects.`;

const SWIFT_TDD_DIRECTIVE = `IMPORTANT: This is a Swift project. Do NOT mandate writing XCTest unit test files first and do NOT create subtasks whose primary output is a test file. Swift tests require the Xcode test runner (xcodebuild test) which cannot be run in this pipeline. Only include test subtasks if the original user task explicitly requests unit or UI tests.`;

const GODOT_TDD_DIRECTIVE = `This is a Godot 4 / GDScript project. Tests run headlessly via execute_bash. After implementing each new feature (cards, enemies, relics, events, mechanics), add corresponding _assert() test cases to tests/TestRunner.gd. Use the existing _assert(label, condition) helper pattern already in that file. Do NOT create new test scene files — add test functions to the existing TestRunner.gd and call them from _ready(). The test subtask should run: GODOT_BIN --headless --path WIN_PATH tests/Test.tscn 2>&1 and confirm exit 0 with the new tests passing.`;

// ---------------------------------------------------------------------------
// Coder directive — injected into the coder system prompt
// ---------------------------------------------------------------------------

/**
 * Returns the max steps for the coder LLM call based on project type.
 * Accepts the pipeline constants as arguments to avoid a circular import.
 */
export function getCoderMaxSteps(projectType, defaultSteps, unitySteps) {
  return projectType === "unity" ? unitySteps : defaultSteps;
}

/**
 * Returns extra coder instructions for the given project type.
 * Always prepends the general directive (dependency triage, cache clearing) so
 * every project type benefits from the abstract principles. Framework-specific
 * directives follow and can override or extend.
 */
export function buildCoderDirective(projectType) {
  const frameworkDirective =
    projectType === "silverstripe" ? SILVERSTRIPE_CODER_DIRECTIVE :
    projectType === "unity"        ? UNITY_CODER_DIRECTIVE :
    projectType === "swift"        ? SWIFT_CODER_DIRECTIVE :
    projectType === "godot"        ? GODOT_CODER_DIRECTIVE : "";
  return GENERAL_CODER_DIRECTIVE + frameworkDirective;
}

// General principles that apply to every project type. Framework-specific
// directives follow and may extend or specialize these.
const GENERAL_CODER_DIRECTIVE = `
DEPENDENCY RESOLUTION TRIAGE:
When a framework reports a missing class/module/type at startup, build, or import time, apply this 2-step triage before editing any code:
1. Test whether the dependency EXISTS independently of the config/build system:
   PHP:    execute_bash("php -r \\"require 'vendor/autoload.php'; echo class_exists('Full\\\\\\\\Name') ? 'EXISTS' : 'MISSING';\\"")
   Node:   execute_bash("ls node_modules/<package-name>")
   Python: execute_bash("python -c \\"import module_name; print('OK')\\"")
   .NET:   execute_bash("grep -r 'class TypeName' src/")
   - EXISTS/found → dependency is installed. The stored REFERENCE FORMAT is wrong (config escaping, missing import, wrong separator). Fix the reference, not the dependency.
   - MISSING/not found → dependency must be installed or created.
2. If EXISTS: inspect the stored reference. Print the exact config value and compare to what the loader expects.
   Common culprits: YAML single-quote escaping (\\\\ = two literal backslashes), JSON double-escaping, wrong namespace separator.

COMPILED ARTIFACT CACHE:
After fixing a dependency reference bug in config/source, clear compiled caches that live OUTSIDE the source tree.
Source reverts alone do NOT clear poisoned compiled caches — bad data was written into the cache on the last failed request.
   PHP/SilverStripe: execute_bash("find /tmp -maxdepth 3 -name 'configcache' -exec rm -rf {} + 2>/dev/null; echo done")
   Node.js:          execute_bash("rm -rf node_modules/.cache .next/cache .vite/cache 2>/dev/null; echo done")
   .NET:             execute_bash("find . \\\\( -name 'obj' -o -name 'bin' \\\\) -exec rm -rf {} + 2>/dev/null; echo done")
   Python:           execute_bash("find . -name '__pycache__' -exec rm -rf {} + 2>/dev/null; echo done")

REACT / WEB UI QUALITY STANDARDS (apply to all React, Vue, and web app tasks):
- SEPARATE CSS FILE: All styles MUST go in a dedicated .css file (e.g. App.css, Calculator.css). Do NOT use inline style objects or style props for layout or theming — use class names and a CSS file. This makes the code maintainable and testable.
- MATHEMATICAL OPERATOR SYMBOLS: Use the correct Unicode characters for display, NOT ASCII keyboard characters:
    Multiplication: × (U+00D7) — NOT "x" or "*"
    Division:       ÷ (U+00F7) — NOT "/"
    Minus:          − (U+2212) — NOT "-" (standard hyphen)
    Plus/minus:     ± (U+00B1)
  Exception: arithmetic computation logic (e.g. JS operators) must still use ASCII. Only the displayed text/labels should use Unicode.
- KEYBOARD SUPPORT: For any interactive tool (calculator, editor, form, game), implement keydown event listeners for all primary actions. A calculator must respond to digit keys, Enter/=, Backspace, Escape (clear), and operator keys (+, -, *, /). For board games (chess, checkers, etc.), implement arrow-key navigation between squares, Enter/Space to select/move, and Escape to deselect. Use useEffect with addEventListener/removeEventListener in React.
- GAME PIECE COLOR CONTRAST: For board games using Unicode piece characters (chess ♔♕♖♗♘♙ vs ♚♛♜♝♞♟, checkers, etc.), white and black pieces MUST use visually distinct CSS colors — do NOT apply a single color to all pieces. White pieces (outline-style glyphs) must use a light color (e.g. #ffffff or #f0d9b5) with a dark text-shadow (e.g. 1px 1px 3px #000). Black pieces (filled glyphs) must use a dark color (e.g. #1a1a1a) with a light text-shadow. A blanket "color: #000000" on ".piece" makes all pieces black and renders white pieces invisible on dark squares. Apply color by piece ownership, not piece class — e.g. ".piece-white { color: #fff; text-shadow: 1px 1px 3px #000; }" and ".piece-black { color: #1a1a1a; text-shadow: 1px 1px 2px rgba(255,255,255,0.6); }".
- OPERATOR ACTIVE STATE: When an operator button is pressed and waiting for the second operand, highlight that operator button with an "active" CSS class so the user can see the pending operation.
- FONT SCALING: If the display value can grow long (numbers, text input), scale the font size down dynamically when the content exceeds a threshold length (e.g. style={{ fontSize: display.length > 10 ? '22px' : '36px' }}).
- EDGE CASES: Always handle: division by zero (show "Error"), floating-point noise (use toPrecision(12) then parseFloat), chained operations (pressing an operator mid-chain should evaluate first), and the decimal point (prevent double dots).
- EXPORTED FUNCTIONS: If the task writes helper functions (math operations, formatters, utilities), export them from their own module (e.g. src/calc.js exports add, subtract, multiply, divide). Import them in the component. This makes unit testing straightforward.
- CSS/JSX CLASS NAME CONSISTENCY (CRITICAL): When writing or updating App.css (or any component CSS), ALL class names in the CSS MUST exactly match the class names used in the JSX. Before writing CSS, read the current JSX to discover the actual class names in use (e.g. className="piece" → .piece { }, className="light-square" → .light-square { }, className="valid-move-square" → .valid-move-square { }). Do NOT invent new class name conventions (e.g. BEM .square.light modifier) unless you ALSO update the JSX to use the matching className="square light" pattern. A CSS file that references class names not present in the JSX is dead code — the styles are never applied. After writing the CSS, verify by checking the JSX for each class name used in the CSS.
- CSS POST-WRITE SELF-CHECK (MANDATORY for React/Vue): After writing any .css file, IMMEDIATELY run this verification:
  1. Read the JSX/TSX component(s) that import the CSS file.
  2. Extract every className string used: e.g. className="board", className="square light-square selected-square".
  3. For each CSS selector in the .css file (e.g. .board, .square, .light-square), confirm it matches a className actually used in the JSX. If NOT found → the selector is dead code and will never apply. Either rename the CSS class to match, or update the JSX className.
  4. Pay special attention to compound selectors: .square.light only matches an element with BOTH classes "square" AND "light" — this is different from .light-square (a single hyphenated class). If JSX uses className="light-square" then the CSS must be .light-square { } not .square.light { }.
  5. If any mismatch is found: fix it before reporting the subtask complete — do NOT leave mismatched selectors in place.
- CSS FILE DISCIPLINE (PREVENTS PROLIFERATION): For each component, ONE CSS file owns its styles. Before writing any CSS:
  1. Search the project for existing CSS files: execute_bash("find {projectDir}/src -name '*.css' | head -20")
  2. If a CSS file for this component already exists (even under a different name like ChessGame.css, Chess.css, or ChessBoard.css), EDIT that file — do NOT create a new one.
  3. The CSS import in the JSX MUST reference whichever file you edited. If the import says "import './App.css'" then edit App.css, not Chess.css.
  4. NEVER create a new CSS file during a retry if ANY css file already exists for this component. Creating Chess.css, ChessGame.css, ChessGame.styles.css, and ChessBoard.css across retries is a pipeline failure — pick one file and fix it in place.
  5. Orphaned CSS files (not imported by any JSX) are dead code. Delete them rather than leaving them.
- NO-OP SUBTASK SELF-CHECK: If a subtask says "run tests and verify" or "run the build" but does NOT require writing files, output [] immediately after running the tools and confirming success. Do NOT write stub files, placeholder files, or package.json markers to satisfy a "must write a file" requirement. The verifier accepts execution-only subtasks (files:[] in the plan) when an execution tool is called.
`;

const SILVERSTRIPE_CODER_DIRECTIVE = `
- SCSS BUILD STEP (CRITICAL — SCSS source changes are NOT live until compiled):
  If you edit any .scss file AND the project has a vite/webpack/sass build system (package.json with "build" script):
  1. After patching or writing the .scss file, IMMEDIATELY run the build: execute_bash("cd {THEME_APP_DIR} && npm run build")
     Where THEME_APP_DIR is the directory containing package.json (e.g. /var/www/auckland/themes/auckland/app).
  2. Verify the compiled output was updated: grep the compiled CSS file (e.g. themes/auckland/app/dist/main.css) for your new selector.
  3. DO NOT report the subtask as complete based on reading the .scss source — the compiled CSS is what the browser sees.
  If you are unsure whether a build step exists: execute_bash("cat {projectDir}/themes/*/app/package.json 2>/dev/null | grep -A2 '\"build\"'")

- CSS :LAST-CHILD SELECTOR CAUTION (prevents wrong selector on CSS grid last-item tasks):
  When adding a :last-child or :nth-last-child rule to a CSS Grid, FIRST read the HTML template to identify ALL direct children of the grid container — not just the repeating items.
  If a non-class-matching element (e.g. a decorative <img>, spacer, or wrapper) appears AFTER the last repeating item in the DOM, then:
  - ".repeating-class:last-child" will NEVER match (last child is the non-matching element)
  - Use ".repeating-class:last-of-type" instead (if all repeating items share the same HTML tag), OR
  - Target the actual last child directly (e.g. "img:last-of-type" if a trailing <img> is the true last child), OR
  - Add a modifier class in the template (<% if $Last %> is-last<% end_if %>) for a precise, HTML-structure-independent hook.
- CSS GRID SPAN-TO-END (prevents gap-fill going to the wrong column):
  To make a CSS Grid item span from wherever it auto-places to the last column, use the LONGHAND:
    "grid-column-start: auto; grid-column-end: -1"
  Do NOT use the shorthand "grid-column: auto / -1". In the shorthand, auto resolves to span-1-from-end = last column only, NOT the auto-placed start position. Using separate longhand properties lets the auto-placement algorithm independently determine the start column, then grid-column-end: -1 spans from there to the last grid line.

- COMPOSER SAFETY (CRITICAL): NEVER run \`composer update\` or \`composer update -W\` without specifying a package name — this upgrades ALL dependencies and may break the site with incompatible versions. ALWAYS use \`composer require package/name:^version\` to add a specific package, or \`composer update package/name\` to update one package only. For SS6 projects: \`dnadesign/silverstripe-elemental\` is already bundled inside \`silverstripe/recipe-cms\` — DO NOT add it separately via Composer. Adding it separately creates duplicate dependency conflicts and triggers unintended full upgrades of all packages.
- DB:BUILD FILESYSTEM ERRORS: If \`vendor/bin/sake db:build --flush\` fails with "League\\\\Flysystem\\\\UnableToSetVisibility", "file_put_contents(...): Permission denied", or any filesystem write error — this is a server permissions issue on public/assets, NOT a code error. Fix FIRST: execute_bash("sudo chown -R www-data:www-data {projectDir}/public/assets && sudo chmod -R 775 {projectDir}/public/assets"), then re-run db:build. If the permissions fix does not resolve it (e.g. the test environment has no www-data user), use the bypass flag: \`vendor/bin/sake db:build --dont_populate --flush\`. The \`--dont_populate\` flag skips the filesystem-intensive populate step (which creates default assets) while still running all schema migrations. Use it as a fallback when permissions cannot be fixed, not as a first resort.
- TEMPLATE INTEGRITY: Before using write_file on any .ss template file, you MUST call read_file on it first. Your write_file MUST include ALL existing markup from the current file - modified only at the locations specified in the scope document. If you are adding a conditional block, use patch_file to wrap existing content. NEVER replace an entire template with a stub.
- TEMPLATE REPLACE vs APPEND (CRITICAL — prevents dual-rendering): When replacing a rendering pattern (e.g. replacing an unconditional \`$Content\` with a conditional Elemental block), you MUST DELETE the old line AND add the new block in one atomic change. If you add the new conditional block WITHOUT removing the existing unconditional \`$Content\`, BOTH will render — the old content always appears AND the new conditional output appears below it. Use patch_file with the exact old content as the match (including the line to delete) so the replacement is precise. After writing, call read_file on the modified template and verify there is only ONE rendering path — if you see both \`$Content\` (unconditional) and the new conditional block, you have a dual-rendering bug and must fix it immediately before proceeding.
- WEB RENDERING: After modifying a .ss template, page class, controller, or DataExtension — MUST verify the site renders. SITE URL DISCOVERY (mandatory before any http_request): read the project root .env file and extract SS_BASE_URL (e.g. grep -E "^SS_BASE_URL" .env). Use that URL for all http_request calls. If SS_BASE_URL is absent, check Apache/nginx vhost config in /etc/apache2/ or /etc/nginx/sites-enabled/ for the ServerName / server_name. Do NOT assume http://localhost — SilverStripe installs run on named vhosts and will return 404 at localhost. Call http_request(url="{DISCOVERED_URL}/?flush=1"). A 500 status means the page is crashing — read the response body to find the exception. A 200 with no exception text = rendering is clean.
- INFRASTRUCTURE REPAIR: If http_request returns HTTP 500 with "file_put_contents(...): Permission denied" or "Unable to write file" or "League\\Flysystem\\UnableToWriteFile" — this is a server filesystem permissions issue, NOT a PHP/YAML/template code error. Fix it with execute_bash BEFORE reporting ACCEPTANCE TEST FAILED: execute_bash("sudo chown -R www-data:www-data {ASSETS_PATH} && sudo chmod -R 775 {ASSETS_PATH}"). The assets path is typically {projectDir}/public/assets. After fixing permissions, retry the http_request — the site should bootstrap correctly. Do NOT report "ACCEPTANCE TEST FAILED" without first attempting the permissions fix.
- YAML CLASS NAME FORMAT (CRITICAL): Write PHP namespaced class names in YAML as UNQUOTED values — no surrounding quotes. Never use single quotes around class names that contain backslashes. Single-quoted YAML strings treat backslash as a literal character, not an escape. A single-quoted YAML class name like 'DNADesign\\\\Elemental\\\\...' gives PHP two literal backslashes per namespace separator. PHP tokenizes DNADesign\\\\Elemental as DNADesign + \\ + \\ElementalPageExtension, causing ExtensionMiddleware to throw "Page references nonexistent \\ElementalPageExtension" even though the class exists. Unquoted YAML passes single backslashes through as the correct PHP namespace separator.
- TEMPLATE POST-WRITE SELF-CHECK: After writing any .ss template file, IMMEDIATELY call read_file on it and scan the output for these patterns:
  1. Is there an unconditional \`$Content\` or \`$Body\` that appears OUTSIDE your new conditional block? If yes: this is a dual-rendering bug — patch_file to remove it.
  2. Is there more than one rendering block (e.g. \`$Content\` on line 8 AND \`<% if $ElementalArea %>\` on line 20)? If yes: only ONE should exist — remove the old one.
  3. Confirm the final template has exactly one content-rendering section that correctly uses the conditional logic you intended.
  Do NOT proceed to db:build or http_request until you have confirmed the template is clean.
- CMS FIELD SUPPRESSION DIAGNOSIS: When the Elemental area or Content field is missing from the CMS edit screen (user reports "Elemental block editor not visible" or "Content tab missing"), run this exact diagnostic before writing any code:
  1. execute_bash("grep -rn 'removeByName' app/src/") — find ALL removeByName calls in the project
     ANY of these suppress CMS fields: removeByName('Content'), removeByName('ElementalArea'), removeByName('ElementalAreaID'), removeByName('Root'), removeByName('Root.Main')
  2. execute_bash("grep -rn 'getCMSFields' app/src/") — find ALL getCMSFields() overrides
     Read each file found. If getCMSFields() does NOT call parent::getCMSFields(), it silently replaces ALL CMS fields — no Elemental, no Content.
  3. execute_bash("grep -rn 'updateCMSFields' app/src/") — find all DataExtension hooks
     Extensions with updateCMSFields() that call removeByName() or tab manipulation can suppress fields.
  Fix pattern: if removeByName('Content') is found in getCMSFields(), DELETE that line. If parent::getCMSFields() is missing, ADD it as the FIRST line of the method.
  IMPORTANT: Do NOT use http_request to verify CMS field visibility — the CMS admin (/admin) requires authentication. After your fix: run_sake db:build --flush and confirm exit 0. That is sufficient — report "ACCEPTANCE TEST PASSED — removeByName removed, db:build clean, extension confirmed in YAML."
- "REFERENCES NONEXISTENT \\ClassName IN 'EXTENSIONS'" DIAGNOSIS: When you encounter this error (from http_request, db:build output, or PHP logs), follow this exact procedure:
  1. Check if the class actually exists: execute_bash("php -r \\"require 'vendor/autoload.php'; echo class_exists('Full\\\\\\\\Namespace\\\\\\\\ClassName') ? 'EXISTS' : 'NOT FOUND';\\"")
     Replace Full\\\\\\\\Namespace\\\\\\\\ClassName with the class from the error (remove any leading \\\\).
     EXISTS = YAML format bug (class is loadable but name is malformed in config)
     NOT FOUND = wrong class name or package not installed
  2. If EXISTS — find the bad YAML entry: execute_bash("grep -rn \\"extensions:\\" app/_config/") then read each _config file. Find the extension entry for the owner class and check if it is wrapped in single quotes.
  3. Fix: remove the single quotes from around the class name so it is unquoted in the YAML.
  4. Clear the compiled config cache: execute_bash("find /tmp -maxdepth 3 -name 'configcache' -exec rm -rf {} + 2>/dev/null; echo done")
     SilverStripe caches compiled config in /tmp/silverstripe-cache-{path}/ — NOT in the project. A flush request writes the broken config into the cache, so git rollback alone does not fix it. You must clear /tmp/ explicitly.
  5. Verify: http_request(url="{DISCOVERED_URL}/?flush=1") — should return HTTP 200.`;

const UNITY_CODER_DIRECTIVE = `
- UNITY BUILD: Do NOT run dotnet build or dotnet test. Unity compiles scripts inside the Editor. Verify C# syntax by reading the file after writing — do not attempt to compile from the CLI.
- UNITY ASSETS: UXML and USS files do not need compilation. Write them directly and confirm the file content is valid XML/CSS syntax.`;

const GODOT_CODER_DIRECTIVE = `
- GODOT SYNTAX CHECK (CRITICAL — run after EVERY .gd file write):
  GODOT_BIN=${GODOT_BIN_PATH}
  WIN_PATH = project dir in Windows format (e.g. C:/Users/Work/card_game, not /mnt/c/... WSL form)
  execute_bash("\\"$GODOT_BIN\\" --headless --path \\"$WIN_PATH\\" --check-only --quit 2>&1")
  Exit 0 + no "SCRIPT ERROR" lines = clean. Fix any error before proceeding.

- DATA FILE FORMAT: JSON files in data/ have specific schemas. ALWAYS read the existing data file before adding new entries — use the exact same field names, nesting, and value types as existing entries. NEVER guess the schema.

- AUTOLOAD ACCESS: Access autoloads by their registered name: GameState.player_hp, CardDB.get_card("strike"). Do NOT use get_node("/root/GameState") or $GameState path syntax.

- SIGNAL CONNECTIONS (Godot 4 ONLY):
  CORRECT: button.pressed.connect(_on_button_pressed)
  CORRECT: button.pressed.connect(func(): _handle(arg))
  WRONG: button.connect("pressed", self, "_on_button_pressed")  ← Godot 3 syntax, DOES NOT WORK in Godot 4

- SCENE REFERENCES: NEVER write to .tscn files — they are managed by the Godot editor. Only modify .gd scripts and data/*.json files.

- PROGRAMMATIC UI (this project builds all UI in code — no UXML/prefabs):
  Create nodes: var lbl = Label.new(); lbl.text = "Hello"; parent.add_child(lbl)
  Sizing: node.custom_minimum_size = Vector2(width, height)
  Theming: node.add_theme_color_override("font_color", Color(1, 0, 0))

- TESTS: After implementing a feature, add test assertions to tests/TestRunner.gd using _assert(label, condition). Run the test suite to verify all tests pass before reporting subtask complete.`;

const SWIFT_CODER_DIRECTIVE = `
- SWIFT BUILD: Do NOT run xcodebuild or swift build. The pipeline cannot resolve signing identities or the full Xcode build graph.
- SWIFT TYPE CHECKING: After writing or patching any .swift file, verify your changes with: execute_bash("swiftc -typecheck -sdk \\"$(xcrun --show-sdk-path)\\" $(find . -name '*.swift' -not -path '*/Pods/*' -not -path '*/.build/*' -not -path '*Tests*') 2>&1"). This catches API errors (wrong modifier on wrong type, missing imports, etc.) that -parse silently misses. Treat any non-module-not-found error as a blocker and fix it. IMPORTANT: if the ONLY remaining errors are "no such module 'UIKit'", do NOT declare clean — UIKit is an iOS-only framework not present in the macOS command-line SDK. UIKit cascade errors MASK other real type errors; fix the UIKit dependency first, then re-run typecheck to reveal hidden errors.
- KNOWN TYPE ERROR — preferredColorScheme on Scene: If you see .preferredColorScheme(...) applied to a WindowGroup { } block (a Scene type), this is a type error. WindowGroup returns some Scene, and preferredColorScheme is a View modifier — not a Scene modifier. Fix: move it inside the WindowGroup content so it applies to the View:
    WRONG: WindowGroup { ContentView() }.preferredColorScheme(.dark)
    RIGHT: WindowGroup { ContentView().preferredColorScheme(.dark) }
    OR:    WindowGroup { Group { ContentView() }.preferredColorScheme(.dark) }
  IMPORTANT: This error is ALWAYS masked by cascade errors in swiftc command-line output — the verifier detects it via static analysis and will REJECT your acceptance test if it is present, even when swiftc -typecheck exits 0. You MUST fix it.
- UIKit CASCADE WARNING: import UIKit in a SwiftUI View file causes "no such module 'UIKit'" on the macOS SDK (UIKit is iOS-only). This error MASKS all other type errors when running swiftc on the command line. If your subtask modifies a file that imports UIKit, and the typecheck returns only UIKit errors, other real errors may be hiding. Fix the UIKit dependency before relying on the typecheck result: either (a) replace UINotificationFeedbackGenerator with SensoryFeedback (iOS 17+), or (b) conditionally guard it. Only after resolving UIKit errors does the typecheck reliably catch all remaining issues.
- Color(.systemBackground) IS A REAL CODE ERROR — NOT AN ENVIRONMENT LIMITATION: Color(.systemBackground) uses UIColor.systemBackground which requires UIKit. When UIKit is not imported, the macOS SDK swiftc reports "reference to member 'systemBackground' cannot be resolved without a contextual type". This is a REAL CODE ERROR that must be fixed — do NOT filter it out with grep -v or declare it ignorable. Options to fix:
    (a) Keep UIKit import: use Color(.systemBackground) with import UIKit — but UIKit causes cascade masking; only viable if UIKit is genuinely needed elsewhere
    (b) UIKit-free fix (PREFERRED): Replace Color(.systemBackground) with one of:
        Color(red: 0.97, green: 0.97, blue: 0.97)  — light system background approximation
        Color(.white).opacity(0.95)
        Color.primary.opacity(0.05)
        Or use @Environment(\.colorScheme) to adapt between light/dark manually
    Choosing option (b) removes the UIKit cascade and lets swiftc typecheck all other errors cleanly.
- ERROR FILTERING IS FORBIDDEN: Do NOT use grep -v, pipe filtering, or any technique to suppress or hide swiftc error output. Do NOT decide on your own that a type error is "an environment limitation" or "macOS SDK vs iOS SDK difference" and declare clean. The ONLY error you may call ignorable is "no such module" for Pods/SPM third-party packages (e.g. Alamofire, Kingfisher). ALL other errors — including "reference to member 'systemBackground'", "type error on WindowGroup", "preferredColorScheme on Scene" — are REAL CODE ERRORS that will be caught by Xcode and rejected by the verifier.
- UIKit ATOMIC REMOVAL — WRITE_FILE, NOT PIECEMEAL PATCH_FILE: When you need to remove import UIKit from a file that also uses UIKit-dependent APIs (Color(.systemBackground), UIPasteboard, UIApplication, UIActivityViewController, UINotificationFeedbackGenerator, etc.), you MUST fix BOTH in a single atomic write_file operation. The patch validator runs swiftc -typecheck after EVERY patch_file call. If you patch_file to remove "import UIKit" alone, the validator immediately catches the revealed UIKit-dependent API errors and ROLLS BACK the patch. The correct sequence: (1) read_file the entire file, (2) mentally replace ALL UIKit APIs with UIKit-free equivalents, (3) write_file the complete updated file with both UIKit import AND UIKit-dependent code replaced atomically. Only then will the patch validator see a coherent state.
- DEPRECATED API — onChange(of:perform:): The iOS 16 single-parameter closure form was deprecated in iOS 17.0 and causes Xcode warnings. The verifier REJECTS acceptance if this pattern is found. Always use:
    WRONG (deprecated, iOS 16): .onChange(of: scenePhase) { newPhase in ... }
    RIGHT (iOS 17+, two params):  .onChange(of: scenePhase) { oldPhase, newPhase in ... }
    RIGHT (iOS 17+, zero params): .onChange(of: scenePhase) { /* use scenePhase directly */ }
  The two-parameter form gives you both old and new values; the zero-parameter form is for when you only need the current value (read it from the environment binding directly).
- SWIFT 6 ACTOR ISOLATION — NotificationCenter closure: NotificationCenter.addObserver closures are typed @escaping @Sendable. Directly referencing @MainActor-isolated properties (@StateObject viewModel, @ObservedObject, etc.) from inside them is a Swift 6 error: "Main actor-isolated property 'X' cannot be referenced from a Sendable closure". The verifier detects this pattern and REJECTS acceptance.
    WRONG (Swift 6 error):
      .onAppear {
        saveObserver = NotificationCenter.default.addObserver(forName: ...) { _ in
          viewModel.saveAllData()  ← ERROR: viewModel is @MainActor, closure is @Sendable
        }
      }
    PREFERRED FIX — eliminate NotificationCenter, use scenePhase onChange instead:
      @Environment(\.scenePhase) var scenePhase
      // In view body modifiers:
      .onChange(of: scenePhase) { oldPhase, newPhase in
          if newPhase == .background { viewModel.saveAllData() }
      }
    ALTERNATIVE FIX — if NotificationCenter is required for other reasons:
      NotificationCenter.default.addObserver(forName: ...) { _ in
          Task { @MainActor in viewModel.saveAllData() }
      }
- NOTIFICATIONCENTER REMOVAL IS MANDATORY WHEN USING SCENEPHASE FIX: When you fix a MainActor isolation error by adding scenePhase .onChange as the replacement, you MUST ALSO remove ALL of the following from the view file that had the NotificationCenter code:
    1. The observer property: "private var saveObserver: NSObjectProtocol?" (or similar)
    2. The .onAppear block that registers the observer: NotificationCenter.default.addObserver(forName: ...) { _ in ... }
    3. The .onDisappear block that deregisters it: NotificationCenter.default.removeObserver(saveObserver!)
    Failing to remove these leaves the broken MainActor isolation code IN PLACE alongside the new scenePhase code. The scenePhase fix in the App struct (*App.swift) does NOT automatically remove the NotificationCenter code from ContentView.swift — you must delete it explicitly. Both will compile but swiftc -strict-concurrency=targeted and the verifier's static analysis will still flag the NotificationCenter closure as a Swift 6 error.
- @Observable MIGRATION IS ATOMIC — ALL FILES IN ONE TURN: @Observable and ObservableObject are MUTUALLY EXCLUSIVE macro systems. Mixing them causes compile errors. When migrating a ViewModel from ObservableObject to @Observable:
    Changes to the class file:    Add @Observable macro, REMOVE : ObservableObject conformance, REMOVE all @Published annotations (they are implicit under @Observable)
    Changes to ALL owner views:   Replace @StateObject var vm = VM()  →  @State var vm = VM()
    Changes to ALL receiver views: Replace @ObservedObject var vm: VM  →  @Bindable var vm: VM
    Changes to ALL environment users: Replace @EnvironmentObject var vm: VM  →  @Environment(VM.self) var vm
  These changes MUST be made in a SINGLE write_file pass across ALL affected files. The patch validator runs swiftc -typecheck after EVERY patch_file call — if you migrate the ViewModel first and plan to update the views in the next subtask, the validator catches the intermediate broken state (@StateObject referencing an @Observable class) and ROLLS BACK the patch. You can never "get there in steps". The ONLY correct approach: write_file the ViewModel + write_file every consuming view + write_file every view that passes it — all in one JSON tool call array.
    WRONG (broken intermediate state):
      Subtask A: write_file StoryViewModel.swift  (add @Observable, remove ObservableObject)
      Subtask B: patch_file ContentView.swift       (@StateObject → @State)   ← patch validator rejects Subtask A before B runs
    RIGHT (atomic):
      Single turn: [write_file StoryViewModel.swift, write_file ContentView.swift, write_file DefinitionPanel.swift]
  The verifier detects @Observable/@ObservableObject mismatch statically and REJECTS acceptance until all consuming files are updated.
- SWIFT FILES: Place new .swift files in the correct directory for the project structure (Sources/<Target>/ for SPM; the named app folder for Xcode projects). Always read_file a nearby existing .swift file first to confirm the naming and import conventions in use.
- STORYBOARD / XIB: .storyboard and .xib files are XML. If you must edit one, read_file it first, make targeted changes, and write_file the result. Do NOT attempt to compile or simulate them.`;

// ---------------------------------------------------------------------------
// Acceptance test directive — injected into the coder system prompt
// ---------------------------------------------------------------------------

/**
 * Returns the ACCEPTANCE TEST instruction for the coder system prompt.
 * Web/PHP/SilverStripe projects use http_request; native Swift apps use execute_bash.
 */
export function buildAcceptanceTestDirective(projectType) {
  if (projectType === "swift")  return SWIFT_ACCEPTANCE_TEST_DIRECTIVE;
  if (projectType === "unity")  return UNITY_ACCEPTANCE_TEST_DIRECTIVE;
  if (projectType === "godot")  return GODOT_ACCEPTANCE_TEST_DIRECTIVE;
  return WEB_ACCEPTANCE_TEST_DIRECTIVE;
}

const WEB_ACCEPTANCE_TEST_DIRECTIVE =
  `- ACCEPTANCE TEST SUBTASKS: For tasks beginning with "ACCEPTANCE TEST:" - do NOT write any files. Use http_request to fetch the URL given in the implementation_note. Search the response HTML for the SUCCESS evidence described in acceptanceCriteria. If found: quote the HTML snippet and report "ACCEPTANCE TEST PASSED — [feature] confirmed: [snippet]". If NOT found: report what IS in the response, diagnose which component is likely missing, and if you can identify a fixable gap (e.g. missing template, missing $ElementalArea, dual-rendering bug) make the fix with write_file/patch_file, re-run db:build if needed, then re-curl. Only report "ACCEPTANCE TEST FAILED" if you cannot identify and fix the gap. CRITICAL RULES: (1) HTTP 200 alone is NOT acceptance — you MUST find the feature-specific HTML in the body. (2) For SilverStripe Elemental: search the response HTML for BOTH the Elemental markup (class="elemental-area" or data-block-type) AND check that the old \`$Content\` block is NOT also rendering unconditionally alongside it. If you see plain-text content output AND elemental-area in the same page, the template has a dual-rendering bug — fix it with patch_file before declaring PASSED. (3) Quote the specific HTML snippet that proves the feature is live — do not just state the HTTP status code.`;

const GODOT_ACCEPTANCE_TEST_DIRECTIVE =
  `- ACCEPTANCE TEST SUBTASKS: For tasks beginning with "ACCEPTANCE TEST:" - do NOT write any files and do NOT use http_request (Godot is a game engine with no HTTP server). Instead, use execute_bash to run the Godot headless test suite:
  GODOT_BIN = ${GODOT_BIN_PATH}
  WIN_PATH = project directory in Windows format (e.g. C:/Users/Work/card_game)
  1. Syntax check: execute_bash("\\"$GODOT_BIN\\" --headless --path \\"$WIN_PATH\\" --check-only --quit 2>&1") — exit 0, no SCRIPT ERROR
  2. Unit tests:   execute_bash("\\"$GODOT_BIN\\" --headless --path \\"$WIN_PATH\\" tests/Test.tscn 2>&1") — exit 0, all pass
  3. Playthrough:  execute_bash("\\"$GODOT_BIN\\" --headless --path \\"$WIN_PATH\\" tests/Playthrough.tscn 2>&1") — exit 0, all pass
  Report: "ACCEPTANCE TEST PASSED — syntax clean, N unit tests passed, M playthrough tests passed"
  If any test fails: read the error output to identify the failing GDScript, fix with write_file/patch_file, re-run.
  CRITICAL: (1) Never use http_request — there is no web server. (2) Quote the test output showing pass/fail counts as evidence. (3) Test count must be >= the count before this task started (adding features MUST add tests).`;

const UNITY_ACCEPTANCE_TEST_DIRECTIVE =
  `- ACCEPTANCE TEST SUBTASKS: For tasks beginning with "ACCEPTANCE TEST:" - do NOT write any files and do NOT use http_request (Unity is a game engine with no HTTP server). Instead, use execute_bash to run Unity batchmode tests, then read the results XML:
  1. execute_bash: run the Unity test runner in batchmode (use the UNITY_BIN path from your system prompt):
     execute_bash("<UNITY_BIN>" -batchmode -projectPath "<PROJECT_DIR>" -runTests -testPlatform editmode -testResults "<PROJECT_DIR>/Logs/editmode_results.xml" -nographics)
  2. read_file: Logs/editmode_results.xml — confirm each required test-case has result="Passed"
  3. Report: "ACCEPTANCE TEST PASSED — [test names] confirmed in editmode_results.xml"
  If tests fail: read the XML to identify failing tests, diagnose the root cause in the C# test or production code, fix with patch_file, then re-run batchmode. Only report "ACCEPTANCE TEST FAILED" if you cannot identify a fix.
  CRITICAL: (1) Never use http_request for Unity acceptance tests — there is no web server. (2) Quote the relevant <test-case> XML lines from editmode_results.xml as evidence. (3) Do not declare PASSED based on placeholder assertions like Assert.IsTrue(true) — tests must verify actual game behaviour.`;

const SWIFT_ACCEPTANCE_TEST_DIRECTIVE =
  `- ACCEPTANCE TEST SUBTASKS: For tasks beginning with "ACCEPTANCE TEST:" - do NOT write any files and do NOT use http_request (this is a native iOS/macOS app with no HTTP server). Instead, use execute_bash to run: (1) Type-check ALL project Swift files together: swiftc -typecheck -strict-concurrency=targeted -sdk "$(xcrun --show-sdk-path)" $(find . -name '*.swift' -not -path '*/Pods/*' -not -path '*/.build/*' -not -path '*Tests*') 2>&1 — exit 0 with no output = no errors or warnings; (2) grep -q "pattern" <file.swift> for each required code pattern from the subtask description. If ALL checks pass: report "ACCEPTANCE TEST PASSED — swiftc type-check clean, all patterns confirmed." If any check fails: diagnose which file/error, fix with patch_file, then re-run. Only report "ACCEPTANCE TEST FAILED" if the issue cannot be fixed. CRITICAL RULES: (1) if the ONLY typecheck errors are "no such module 'UIKit'" — do NOT declare clean. UIKit is not available in the macOS SDK and this error MASKS real errors behind it. You must fix the UIKit import before the typecheck can be trusted. "no such module" for Pods/SPM packages (not UIKit) are ignorable — all UIKit-related and all other non-module errors must be fixed. (2) ERROR FILTERING IS ABSOLUTELY FORBIDDEN: Do NOT pipe swiftc output through grep -v, sed, or any filter to suppress specific errors. Do NOT decide that "reference to member 'systemBackground'" or any other type error is an "environment limitation" or "iOS vs macOS SDK difference" and filter it out. The verifier runs swiftc -typecheck independently and will REJECT your claim if any non-Pods errors are present. (3) The verifier ALSO runs static analysis and will FAIL for: .preferredColorScheme outside a WindowGroup block; .onChange(of:) single-parameter closure (deprecated iOS 17); NotificationCenter.addObserver closures that access @MainActor viewModel directly; @Observable class referenced via @StateObject or @ObservedObject in any consuming view. These are caught even when swiftc exits 0. (4) WARNINGS matter: run the command and inspect ALL output — swiftc deprecation warnings emit to stderr with exit code 0. If ANY output remains after filtering "no such module" lines, the project is NOT clean.`;

// ---------------------------------------------------------------------------
// Planner verification directive — injected into the planner system prompt
// ---------------------------------------------------------------------------

/**
 * Returns framework-specific guidance for the planner's verification subtask examples.
 * Injected after the generic VERIFICATION SUBTASK RULE.
 */
export function buildPlannerVerificationDirective(projectType) {
  if (projectType === "silverstripe") return SILVERSTRIPE_PLANNER_VERIFICATION;
  if (projectType === "swift")        return SWIFT_PLANNER_VERIFICATION;
  if (projectType === "unity")        return UNITY_PLANNER_VERIFICATION;
  if (projectType === "godot")        return GODOT_PLANNER_VERIFICATION;
  return "";
}

const UNITY_PLANNER_VERIFICATION = `
For Unity projects the LAST subtask MUST be an acceptance test using execute_bash evidence — NOT http_request (Unity is a game engine with no HTTP server):
- The acceptanceCriteria MUST say: "execute_bash Unity batchmode: <UNITY_BIN> -batchmode -projectPath <PROJECT_DIR> -runTests -testPlatform editmode -testResults <PROJECT_DIR>/Logs/editmode_results.xml -nographics. Then read_file Logs/editmode_results.xml and confirm <test-case name='[TestName]' result='Passed' />."
- The implementationNote MUST NOT contain any http:// URL — no http_request is possible on a Unity project.
- NEVER write "HTTP request" or "http_request" in any Unity acceptance test criteria.

Example:
  task: "ACCEPTANCE TEST: Verify hit effects and camera tracking"
  acceptanceCriteria: "execute_bash Unity batchmode test runner exits 0 AND read_file Logs/editmode_results.xml confirms <test-case name='EffectSpawnTest' result='Passed' /> and <test-case name='CameraTrackingTest' result='Passed' />."
  failureCriteria: "editmode_results.xml shows any test as Failed or missing, or batchmode exits non-zero."`;

const GODOT_PLANNER_VERIFICATION = `
For Godot projects the LAST subtask MUST be an acceptance test using execute_bash evidence — NOT http_request (Godot is a game engine with no HTTP server):
- GODOT_BIN = ${GODOT_BIN_PATH}
- WIN_PATH = project path in Windows format (e.g. C:/Users/Work/card_game)
- The acceptanceCriteria MUST say: "execute_bash: GODOT_BIN --headless --path WIN_PATH tests/Test.tscn 2>&1 exits 0 AND shows N passed, 0 failed. Also run Playthrough.tscn and confirm 0 failures."
- The implementationNote MUST include the exact execute_bash commands with GODOT_BIN and WIN_PATH filled in.
- NEVER write "http_request" or any URL in a Godot acceptance test.
- The test count in the acceptance result MUST be >= the baseline (features must add test coverage).

Example:
  task: "ACCEPTANCE TEST: Verify new enemy types pass all unit and playthrough tests"
  acceptanceCriteria: "execute_bash Godot headless exits 0 AND test output shows 130+ passed, 0 failed."
  failureCriteria: "test output shows any failure or Godot exits non-zero."`;

const SILVERSTRIPE_PLANNER_VERIFICATION = `
For SilverStripe projects the verification subtask MUST include a page render check:
- First discover SS_BASE_URL from the project .env file (grep -E "^SS_BASE_URL" .env)
- Run: vendor/bin/sake db:build --flush to rebuild and flush template cache
- Then: use http_request(url="{DISCOVERED_URL}/?flush=1") — confirm 200 status, no exceptions in body
- If the error was on a specific page (e.g. GET /events/my-event), test that URL too
- A 500 HTTP response or any exception in the body = FAIL; must fix and re-test

Examples:
- "fix the db:build error" → last subtask: "Run vendor/bin/sake db:build, then use http_request to confirm HTTP 200 with no exceptions"
- "fix a template rendering error on GET /" → last subtask: "Run vendor/bin/sake db:build --flush, then http_request the base URL and confirm no exception/fatal in body"`;

const SWIFT_PLANNER_VERIFICATION = `
For Swift projects the LAST subtask SHOULD be an acceptance test using bash-only evidence — NOT http_request (native apps have no HTTP server):
- Run: execute_bash type-check all source files together: swiftc -typecheck -strict-concurrency=targeted -sdk "$(xcrun --show-sdk-path)" $(find . -name '*.swift' -not -path '*/Pods/*' -not -path '*Tests*') 2>&1 (exit 0 with no output = no errors or warnings; "no such module" errors from Pods are ignorable)
- IMPORTANT: also inspect the output even when exit code is 0 — deprecation warnings (e.g. "'onChange(of:perform:)' was deprecated") emit to stderr with exit 0 and must be fixed
- Run: execute_bash grep -q "pattern" <file.swift> to confirm required code patterns are present
- Report: "ACCEPTANCE TEST PASSED" if all checks succeed

Example: "ACCEPTANCE TEST: Verify Swift files type-check cleanly and required patterns are present"
  → last subtask executes swiftc -typecheck -strict-concurrency=targeted on all source files, grep for key patterns, reports PASSED/FAILED

MANDATORY PRE-FLIGHT FIX RULE: If the research snapshot KEY FINDINGS SUMMARY includes "EXISTING TYPE ERRORS", "KNOWN TYPE ERROR", "DEPRECATED API", or "CONCURRENCY ISSUE":
- The VERY FIRST subtask MUST be "Fix pre-existing Swift type errors and API issues in [filename(s)]" addressing ALL listed issues
- Do NOT create feature implementation subtasks until all existing errors are resolved — type errors compound and mask each other
- Known patterns to ALWAYS create a dedicated fix subtask for (even when NOT the primary task):
  • "KNOWN TYPE ERROR: .preferredColorScheme on Scene" → MANDATORY subtask: "Fix preferredColorScheme type error in [*App.swift filename]: move .preferredColorScheme inside the WindowGroup content block". The implementation_note MUST include the exact file path (from research output), the exact wrong line, and the required fix:
      WRONG: WindowGroup { Group { ContentView() } }.preferredColorScheme(...)
      RIGHT: WindowGroup { Group { ContentView() }.preferredColorScheme(...) }
    The verifier uses static analysis — it will ALWAYS reject acceptance if not fixed.
  • UIKit import in a pure SwiftUI View file → create subtask to ATOMICALLY remove UIKit and replace all UIKit-dependent APIs in a single write_file. The implementation_note must list each UIKit-dependent call and its replacement (e.g. Color(.systemBackground) → Color(red: 0.97, green: 0.97, blue: 0.97); UINotificationFeedbackGenerator → remove; UIPasteboard → remove or replace with ShareLink). Do NOT patch_file UIKit removal separately from UIKit API replacement — the patch validator catches the revealed errors and rolls back.
  • "DEPRECATED API: onChange(of:)" → create subtask to fix ALL .onChange(of:) calls to use two-parameter form: .onChange(of: value) { oldVal, newVal in ... }
  • "CONCURRENCY ISSUE: NotificationCenter + viewModel" → create subtask to replace NotificationCenter.addObserver pattern with scenePhase .onChange modifier (preferred) or wrap viewModel calls with Task { @MainActor in ... }
- If research warns "UIKit import may be masking additional type errors", the UIKit-removal subtask MUST come BEFORE any other subtask, so subsequent type-checks reveal all hidden errors

  • "OBSERVABLE MISMATCH: [ViewModel] is @Observable but consuming views use @StateObject/@ObservedObject" → create ONE ATOMIC subtask that writes_file ALL affected files simultaneously:
    - The ViewModel file: add @Observable, remove : ObservableObject, remove all @Published annotations
    - Every owner view: @StateObject var vm = VM() → @State var vm = VM()
    - Every receiver view: @ObservedObject var vm: VM → @Bindable var vm: VM
    The subtask implementation_note MUST list every file that will be touched. This CANNOT be split across multiple subtasks — the patch validator rejects intermediate broken states.

CRITICAL: The verifier independently detects four additional issues via static analysis, independent of swiftc output:
1. .preferredColorScheme outside (after) a WindowGroup block — always rejected even when swiftc exits 0
2. .onChange(of:) single-parameter closure (deprecated iOS 17) — always rejected even when swiftc exits 0
3. NotificationCenter.addObserver closure accessing @MainActor viewModel directly (Swift 6 error)
4. @Observable class referenced via @StateObject or @ObservedObject in any consuming view — always rejected
There is no way to "pass" acceptance without fixing ALL of these — the planner MUST schedule fix subtasks for each one found in research.`;

// ---------------------------------------------------------------------------
// Build command detection — used by format.js and verifierNode.js
// ---------------------------------------------------------------------------

/**
 * Regex that matches framework-specific build / flush commands.
 * Used to decide whether to apply noise-stripping and to detect execution evidence.
 */
export const BUILD_COMMAND_RE = /dev\/build|db:build|sake/;

// ---------------------------------------------------------------------------
// Asset extensions — used by verifierNode.js
// ---------------------------------------------------------------------------

/**
 * Unity UI Toolkit asset files are implementation output, not documentation.
 * They don't require C# compilation but must not be treated as docs-only.
 */
export const UNITY_ASSET_EXTENSIONS = new Set([".uxml", ".uss", ".asmdef", ".asmref"]);

/**
 * Swift/Xcode asset and layout files are implementation output.
 * .storyboard and .xib are XML UI layouts; .xcassets are asset catalog dirs.
 * They don't require Swift compilation but must not be treated as docs-only.
 */
export const SWIFT_ASSET_EXTENSIONS = new Set([".storyboard", ".xib", ".xcassets", ".strings", ".stringsdict"]);
